apiVersion: v1
kind: Pod
metadata:
   name: tomcat9
   labels:
     zone: prod
     version: v1
spec:
   containers:
   - name: tomcat9
     image: ohyoungjooung2/tomcat9.0.10-on-alpinelinux38
     ports:
     - containerPort: 8080
