apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actuator-sample
spec:
  replicas: 2
  template:
     metadata:
       labels:
         app: actuator-sample
     spec:
       containers:
       - name: actuator-sample
         #image: registry.gitlab.com/marcolenzo/actuator-sample
         image: 10.1.0.7:5000/actuator-sample
         imagePullPolicy: Always
         ports:
         - containerPort: 10000
       imagePullSecrets:
         #- name: registry.gitlab.com
         - name: 10.1.0.7:5000
